# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/InfoScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QObject
from DatetimeLabel import *
from TSO_State import TSO_State
import requests


SLEEP_DELAY = 3


class Logic(QObject):
    new_screen = pyqtSignal(object)
    stop_timer = pyqtSignal()

    def __init__(self, inscription, screen=None):
        super(Logic, self).__init__()
        self.inscription = inscription
        self.data = None
        self.actual = True
        self.screen = screen

    def run(self):
        if self.inscription == "Загрузка":
            try:
                r = requests.get('http://127.0.0.1:8000/api/v1/TSO/pumps/')
            except requests.exceptions.ConnectionError:
                print('ERROR')
                return
            # print(r)
            if r.status_code == 200:
                self.data = r.json()
            print(r.status_code)
            QtCore.QThread.msleep(SLEEP_DELAY * 1000)
        elif self.inscription == "Следуйте инструкциям на пин-паде":
            QtCore.QThread.msleep(SLEEP_DELAY * 1000)
            pass
        elif self.inscription == "Подождите, идёт печать":
            self.data = self.screen.data
            del self.data['inscription_num']
            QtCore.QThread.msleep(SLEEP_DELAY * 1000)
            self.screen.choice_of_inscription(3)
            QtCore.QThread.msleep(SLEEP_DELAY * 1000)
            try:
                r = requests.post('http://127.0.0.1:8000/api/v1/TSO/orderpetrol/', json=self.data)
            except requests.exceptions.ConnectionError:
                print('ERROR')
                return
            if r.status_code == 400 and "Pump is BUSY now!" in r.text:
                self.screen.horizontalLayout_2.removeWidget(self.screen.label_5)
                self.screen.horizontalLayout_2.removeWidget(self.screen.label_6)
                self.screen.label_5.hide()
                self.screen.label_6.hide()
                self.stop_timer.emit()
                while r.status_code == 400 and "PumpState is irrelevant!" not in r.text:
                    self.screen.choice_of_inscription(5)
                    QtCore.QThread.msleep(SLEEP_DELAY * 1000)
                    r = requests.post('http://127.0.0.1:8000/api/v1/TSO/orderpetrol/', json=self.data)
                    print('try')

                if r.status_code == 400:
                    self.data['pump']['status'] = 'FREE'
                    try:
                        r = requests.post('http://127.0.0.1:8000/api/v1/TSO/orderpetrol/', json=self.data)
                    except requests.exceptions.ConnectionError:
                        print('ERROR')
                        return

            if r.status_code == 200:
                self.screen.choice_of_inscription(2)
                QtCore.QThread.msleep(SLEEP_DELAY * 1000)
                self.screen.choice_of_inscription(4)
                QtCore.QThread.msleep(SLEEP_DELAY * 1000)

            self.data = r
            print(r)
        if self.actual:
            self.new_screen.emit(self.data)
        self.thread().quit()


class InfoScreen(QtWidgets.QMainWindow):
    def __init__(self, state, data):
        from MainScreen import MainScreen
        from ErrorScreen import ErrorScreen
        from PumpsScreen import PumpsScreen
        super(InfoScreen, self).__init__()
        self.setupUi()
        self.state = state
        inscription_num = data['inscription_num']
        self.choice_of_inscription(inscription_num)
        self.data = {} if inscription_num == 0 else data

        self._dictButtons = {
            'mainScreen': ('mainScreen', MainScreen),
            'errorScreen': ('errorScreen', ErrorScreen),
            'pumpsScreen': ('pumpsScreen', PumpsScreen)
        }

        self.init_timer()

        self.init_logic()
        self.thread.start()
        # self.process = QtCore.QTimer()
        # self.process.timeout.connect(self.start_process)
        # self.process.start(1)
        # self.c = Communicate()
        # self.c.new_screen.connect(self.showScreen)
        # self.start_process()

        print(self.data)

    def init_logic(self):
        self.thread = QtCore.QThread(self)
        self.logic = Logic(self.get_inscription(), self)
        self.logic.moveToThread(self.thread)
        self.logic.new_screen.connect(self.showScreen)
        self.logic.stop_timer.connect(self.stop_timer)
        self.thread.started.connect(self.logic.run)

    def init_timer(self):
        self.delay_timer = QtCore.QTimer()
        self.delay_timer.timeout.connect(self.showScreen)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_timedelay)
        self.decrease = 0
        set_current_time(self.label_6, self.decrease)
        self.delay_timer.start(TIMER_DELAY * 1000)
        self.timer.start(1 * 1000)

    def update_timedelay(self):
        self.decrease += 1
        set_current_time(self.label_6, self.decrease)

    def update_data(self):
        self.data['terminalNumber'] = self.state.TSO_number
        self.data['id'] = self.state.id

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(873, 662)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def choice_of_inscription(self, inscription_num):
        inscription_list = ["Загрузка",
                           "Следуйте инструкциям на пин-паде",
                           "Подождите, идёт печать",
                           "Возьмите напечатанную квитанцию заказа",
                           "Возьмите напечатанный чек",
                           "ТРК занята. Ожидайте пока ТРК освободится."]

        inscription = inscription_list[inscription_num]
        self.label.setText(inscription)
        #print(inscription)

    def get_inscription(self):
        return self.label.text()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("InfoScreen", "InfoScreen"))
        self.label_5.setText(_translate("MainWindow", "Возврат в главное меню через:"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))

    def stop_timer(self):
        self.delay_timer.stop()
        self.timer.stop()

    def terminate_logic(self):
        self.logic.actual = False
        if self.thread.isRunning():
            print('if')
            self.thread.quit()
            self.thread.wait()
            self.thread.terminate()
            self.thread.wait()
        print(self.thread.isFinished(), self.thread.isRunning())

    def decrease_id(self):
        self.state.id += 1

    def create_inscription(self, inscription):
        return {'inscription': inscription}

    def showScreen(self, data=None):
        self.stop_timer()
        self.terminate_logic()

        print(data)
        if data and type(data) != requests.models.Response:
            self.update_data()
            self.data['pump'] = data

        sender = self.sender()
        if sender == self.delay_timer:
            screen_name, screen_class = self._dictButtons['mainScreen']
            #self.logic.actual = False
        elif type(data) == requests.models.Response:
            if data.status_code == 200:
                screen_name, screen_class = self._dictButtons['mainScreen']
            elif data.status_code == 400 or 503:
                screen_name, screen_class = self._dictButtons['errorScreen']
                inscription = data.text if data.status_code == 400 else "Нет связи с ТРК. Заправка невозможна!"
                self.data = self.create_inscription(inscription)

            self.decrease_id()
        elif 'pump' not in self.data.keys():
            screen_name, screen_class = self._dictButtons['errorScreen']
            inscription = "Нет связи с ТРК. Заправка невозможна!"
            self.data = self.create_inscription(inscription)
        elif self.data['pump']:
            screen_name, screen_class = self._dictButtons['pumpsScreen']

        setattr(self, screen_name, screen_class(self.state, self.data))
        _screen = getattr(self, screen_name, None)
        _screen.show()
        self.close()
        #print('close')


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    state = TSO_State(currencydetector=False)
    data = {
        'inscription_num': 0
    }
    ui = InfoScreen(state, data)
    ui.show()
    sys.exit(app.exec_())
